config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin/cms'
  mount RailsEmailPreview::Engine, at: 'admin/emails'
  resources :appointments, only: [:index] do
    collection do
      get :by
    end
  end

  get 'sign_in' => 'home#sign_in'

  resources :users do
    post 'update_roles', on: :collection
  end
  resources :drives, only: [:show] do
    resources :appointments, except: [:index] do
      post :remind, on: :member
    end
    member do
      get 'kiosk'
      post 'add_appointment'
    end
  end
  resources :drives, only: [:edit, :update, :index]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  namespace :admin do
    resources :drives, only: [:show] do
      resources :appointments, only: [:index]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/drive.rb
class Drive < ActiveRecord::Base
  has_many :days, dependent: :destroy
  has_many :appointments, dependent: :destroy
  accepts_nested_attributes_for :days, allow_destroy: true, reject_if: proc {|attrs| attrs['start_time'].blank? && attrs['stop_time'].blank?}

  validates :name, :contact_email, presence: true

  scope :opened, -> {where('open_at IS NOT NULL AND open_at < ?', Time.now)}
  scope :closed, -> {where('close_at IS NOT NULL AND close_at < ?', Time.now)}
  scope :not_closed, -> {where('close_at IS NULL OR close_at > ?', Time.now)}
  scope :active, -> {opened.not_closed}

  rails_admin do
    edit do
      field :name
      field :location
      field :contact_email
      field :max_per_slot
      field :time_per_slot
      field :open_at
      field :close_at
    end
  end

  def opened?
    open_at && open_at < Time.now
  end

  def not_closed?
    close_at.nil? || close_at > Time.now
  end

  def active?
    opened? && not_closed?
  end
end

app/controllers/drives_controller.rb
class DrivesController < ApplicationController
  before_action :require_user

  def kiosk
    @drive = Drive.find params[:id]
    @appointment = @drive.appointments.build
    @appointment.build_user
    authorize @drive, :kiosk?
  end

  def add_appointment
    @drive = Drive.find params[:id]
    @appointment = @drive.appointments.build new_appointment_params
    @lookup_by_email = @appointment.user.lookup_by_email?
    @appointment.find_or_create_user!
    @appointment.user.save
    if @appointment.save
      flash[:success] = "Added an appointment for #{@appointment.user.display}"
      redirect_to action: 'kiosk'
    else
      unless @lookup_by_email
        flash.now[:error] = @appointment.errors.full_messages.to_sentence
      end
      render action: 'kiosk'
    end
  end

  def index
    # TODO: pagination
    if current_admin
      @drives = Drive.order('created_at DESC')
    elsif current_user
      @drives = current_user.drives.order('created_at DESC')
    end
  end

  def show
    @drive = Drive.find params[:id]
  end

  def edit
    @drive = Drive.find params[:id]
    @drive.days.build
  end

  def update
    @drive = Drive.find params[:id]
    if @drive.update_attributes drive_params
      flash[:success] = "Changes saved."
      redirect_to edit_drive_path(@drive)
    else
      render 'edit'
    end
  end

  private
  def drive_params
    params.require(:drive).permit!
  end

  def new_appointment_params
    params.require(:appointment).permit(
      :double_red, :slot_time, :day_id, :day_slot,
      user_attributes: [:id, :netid, :email, :fname, :lname, :class_year, :college, :lookup_by_email, :phone]
    )
  end
end

app/helpers/drives_helper.rb
module DrivesHelper
end

app/views/drives/_confirmed.html.slim
.panel.panel-primary
  .panel-heading
    h1.panel-title Donor list
  .panel-body
    p.text-success Click on a donor to change/remove their appointment
    - drive.days.each do |day|
      - if day.persisted?
        table.table.table-condensed
          thead
            tr
              th style="width:120px" = day.date
              th Donors
          tbody
            - day.available_slots.each do |slot|
              tr id=(slot_row_id(day, slot)) class=('warning text-muted' if day.slot_full?(slot))
                td
                  =<> slot.strftime(Time::DATE_FORMATS[:am_pm])
                  .badge = day.slot_status(slot)
                td
                  - day.appointments_at(slot).each do |appt|
                    = link_to appt.user.email_or_netid, edit_drive_appointment_path(drive, appt), class: "label label-#{appt.double_red? ? 'danger' : 'default'}", target: '_blank'

app/views/drives/_drive_image.html.slim
= link_to drive, class: 'thumbnail' do
  - if drive.filepicker_url?
    = filepicker_image_tag drive.filepicker_url, w: 300, h: 300, fit: 'clip'
  - else
    = image_tag "http://placehold.it/300/fff&text=Coming+soon!"

app/views/drives/_drive_info.html.slim
.panel.panel-primary
  .panel-heading
    h1.panel-title = link_to drive.name, drive
  .panel-body
    = render 'drives/drive_image', drive: drive
    - drive.days.each do |day|
      .drive-day
        .day-date
          h3 style="margin-top:0"
            = day.date.to_s(:day_long)
        .day-time
          => am_pm day.start_time
          ' -
          = am_pm day.stop_time
  .panel-footer
    h2.drive-location.panel-title
      strong> Location:
      = drive.location

app/views/drives/edit.html.erb
<%= filepicker_js_include_tag %>
<h1>
  Edit Drive
  <% if @drive.active? %>
    <span class="label label-primary">active</span>
  <% else %>
    <span class="label label-default">inactive</span>
  <% end %>
  <small><%= link_to "See Kiosk", kiosk_drive_path(@drive), class: 'btn btn-default btn-sm' %></small>
  <small><%= link_to "View Drives", drives_path, class: 'btn btn-default btn-sm' %></small>
</h1>

<%= simple_form_for @drive do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :contact_email %>
  <% if f.object.filepicker_url.present? %>
    <div class="thumbnail">
      <%= filepicker_image_tag f.object.filepicker_url, w: 160, h: 160, fit: 'clip' %>
  </div>
  <% end %>
  <p>
    <%= f.filepicker_field :filepicker_url, class: 'btn btn-success', button_text: "Insert Image" %>
    <span class="hint text-warning">Please save changes after inserting or changing an image</span>
  </p>
  <div class="row">
    <div class="col-xs-6">
      <%= f.input :max_per_slot %>
    </div>
    <div class="col-xs-6">
      <%= f.input :time_per_slot %>
    </div>
  </div>
  <%= f.input :open_at %>
  <%= f.input :close_at %>
  <div class="row">
    <div class="col-sm-8">
     <%= f.simple_fields_for :days, html: {form: 'form-horizontal'} do |d| %>
        <div class="panel panel-<%= d.object.persisted? ? 'primary' : 'default' %>">
          <div class="panel-heading">
            <h1 class="panel-title">
              <% if d.object.persisted? %>
                Day #<%= d.index + 1 %>
              <% else %>
                Add A Day
              <% end %>
            </h1>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-4">
                <%= d.label :date %>
                <%= d.date_field :date, placeholder: 'Date', value: d.object.date || Date.today %>
              </div>
              <div class="col-xs-4">
                <%= d.label :start_time %>
                <%= d.time_field :start_time, value: d.object.start_time && d.object.start_time.strftime("%H:%M:%S") %>
              </div>
              <div class="col-xs-4">
                <%= d.label :stop_time %>
                <%= d.time_field :stop_time, value: d.object.stop_time && d.object.stop_time.strftime("%H:%M:%S") %>
              </div>
            </div>
            <% if d.object.persisted? %>
              <div class="checkbox">
                <label class="text-danger"><%= d.check_box :_destroy %>Remove</label>
              </div>
              <% if d.object.confirmed_appointment_count > 0 %>
                <div class="alert alert-danger" style="margin-bottom:0">
                  <strong>Warning:</strong> There are <%= pluralize d.object.confirmed_appointment_count, 'confirmed appointment' %> for this day. 
                  Removing this day will remove those slots.
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
    <div class="col-sm-4">
      <%= render 'confirmed', drive: @drive %>
    </div>
  </div>
<% end %>

app/views/drives/index.html.slim
- if current_admin
  h1 Drives
- else
  h1 My Drives

table.table
  thead
    tr
      th
      th Name
      th Open at
      th Close at
      th Location
      th Contact Email
      th Beds/slot
      th Slot Duration (min)
      th Created At
  tbody
    - @drives.each do |drive|
      tr class=('info' if drive.active?)
        td.drive-row = render 'drives/drive_image', drive: drive
        td = link_to drive.name, drive
        td
          - if drive.open_at
            .timestamp [
              class=('text-primary' if drive.open_at < Time.now)
              class=('text-info' if drive.open_at > Time.now)
            ]
              = time_vs_now(drive.open_at)
          - else
            | Not set
        td
          - if drive.close_at
            .timestamp [
              class=('text-danger' if drive.close_at < Time.now)
              class=('text-primary' if drive.close_at > Time.now)
            ]
              = time_vs_now(drive.close_at)
          - else
            | Not set
        td = drive.location
        td = drive.contact_email
        td = drive.max_per_slot
        td = drive.time_per_slot
        td
          .timestamp = drive.created_at.to_s(:am_pm_long)
          .timestamp = time_vs_now(drive.created_at)
        - if staff_access?
          td
            = link_to "Edit Days", edit_drive_path(drive), class: 'btn btn-default btn-sm btn-block'
            = link_to "Appointments", admin_drive_appointments_path(drive), class: 'btn btn-default btn-sm btn-block'
            = link_to "Kiosk", kiosk_drive_path(drive), class: 'btn btn-default btn-sm btn-block'

- if current_admin
  = link_to "New Drive", "/admin/drive/new", class: 'btn btn-primary'

app/views/drives/kiosk.html.slim
.row
  .col-xs-6
    h1 = @drive.name
  .col-xs-6
    - if @drive.filepicker_url?
      = filepicker_image_tag @drive.filepicker_url, w: 300, h: 300
hr
h1.text-center
  .label.label-danger Kiosk Mode
hr

#save-status.label.label-success style="display:none"
  | Changes saved.

#appointment-form
  = simple_form_for [@drive, @appointment], url: add_appointment_drive_path(@drive) do |f|
    .row
      .col-sm-4
        .panel.panel-primary
          .panel-heading
            h1.panel-title Donor's Information
          .panel-body
            - if @appointment.user_id
              p.text-danger Make sure the user's data is up to date and the netid is correct.
            - else
              p.text-success If you have a yale email address and check the lookup box, we can auto-fill the names
            = f.simple_fields_for :user do |u|
              = render 'appointments/user_fields', u: u
              = f.input :double_red, label: "Donating double reds?", hint: link_to("(Learn more about double red here)", 'http://www.redcrossblood.org/donating-blood/types-donations/double-red-blood-cells-donation', target: '_blank')
              - if u.object.persisted?
                = link_to "Clear User", kiosk_drive_path(@drive), class: 'btn btn-default pull-right'
            => f.submit "Save Changes", class: 'btn btn-primary', data: {disable_with: 'Saving...'}
      .col-sm-4
        - @drive.days.each do |day|
          = render 'appointments/day_slots', day: day, f: f
        = f.submit nil, class: 'btn btn-primary sr-only'
      .col-sm-4
        = render 'confirmed', drive: @drive

coffee:
  $('.slot-picker > label.btn').click ->
    elem = $(this).data('row-ref')
    $(elem).addClass('info text-primary').siblings().removeClass('info text-primary')
  $('#email-lookup').on 'change', ->
    $(this).parents('form').submit()

app/views/drives/show.html.slim
= render 'drives/drive_info', drive: @drive

.row
  .col-xs-6
    = link_to "Make an appointment", new_drive_appointment_path(@drive), class: 'btn btn-danger btn-block btn-lg'
  - if staff_access?
    .col-xs-3
      = link_to "Sign others up (Kiosk)", kiosk_drive_path(@drive), class: 'btn btn-primary btn-block btn-lg'
    .col-xs-3
      = link_to "View appointments", admin_drive_appointments_path(@drive), class: 'btn btn-info btn-block btn-lg'