config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin/cms'
  mount RailsEmailPreview::Engine, at: 'admin/emails'
  resources :appointments, only: [:index] do
    collection do
      get :by
    end
  end

  get 'sign_in' => 'home#sign_in'

  resources :users do
    post 'update_roles', on: :collection
  end
  resources :drives, only: [:show] do
    resources :appointments, except: [:index] do
      post :remind, on: :member
    end
    member do
      get 'kiosk'
      post 'add_appointment'
    end
  end
  resources :drives, only: [:edit, :update, :index]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  namespace :admin do
    resources :drives, only: [:show] do
      resources :appointments, only: [:index]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :day
  belongs_to :drive

  serialize :slot_time, Tod::TimeOfDay

  accepts_nested_attributes_for :user
  validates :slot_time, presence: true

  delegate :date, to: :day

  def exact_time
    if slot_time and day
      slot_time.on day.date
    end
  end

  def confirmed?
    !!slot_time
  end

  def match_slot?(some_day, some_slot)
    day == some_day && slot_time == some_slot
  end

  def day_slot
    "#{day_id}@#{slot_time.strftime('%H:%M:%S')}"
  end

  def day_slot=(value)
    self.day_id, self.slot_time = *value.split('@')
  end

  def find_or_create_user!
    if user.netid.present? && record = User.where(netid: user.netid).first
      self.user_id = record.id
    elsif user.email.present? && record = User.where(email: user.email).first
      self.user_id = record.id
    end
  end

  def user_attributes=(user_attrs)
    self.user = User.find_or_initialize_by(id: user_attrs.delete(:id))
    self.user.attributes = user_attrs
  end

  def remind!
    if user.email.present?
      AppointmentMailer.reminder(id).deliver_now!
      self.update_column :last_reminded_at, Time.now
    end
  end
end

app/controllers/admin/appointments_controller.rb
class Admin::AppointmentsController < Admin::BaseController
  @access_level = 'staff'
  helper_method :sorting_column
  helper_method :sorting_direction

  def index
    @drive = Drive.find params[:drive_id]
    @appointments = @drive.appointments.includes(:user, :day).order(sorting)
  end

  private

  def sorting
    column = sorting_column
    "#{column} #{sorting_direction}"
  end

  def sorting_column
    params[:sort][/^\-?(.+)/, 1] if params[:sort].present?
  end

  def sorting_direction
    params[:sort] =~ /^\-/ ? :desc : :asc if params[:sort].present?
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :require_user
  before_action :load_drive, except: [:index, :by]

  def index
    @appointments = current_user.appointments
  end

  def by
    authorize :appointments
    @user = User.find params[:user_id]
    @appointments = @user.appointments
  end

  def new
    scope = Appointment.where(user: current_user, drive: @drive)
    @appointment = scope.first || scope.build
    @appointment.save(validate: false) unless @appointment.persisted?
    redirect_to edit_drive_appointment_path(@drive, @appointment)
  end

  def edit
    @appointment = @drive.appointments.find params[:id]
  end

  def update
    @appointment = Appointment.find params[:id]
    if params[:appointment]
      @appointment.update_attributes appointment_params
    end

    respond_to do |format|
      format.html do
        redirect_to action: 'edit', id: @appointment.id
      end
      format.js
    end
  end

  def destroy
    @appointment = @drive.appointments.find params[:id]
    @appointment.destroy
    redirect_to @drive
  end

  def remind
    @appointment = @drive.appointments.find params[:id]
    @appointment.remind!

    respond_to do |format|
      format.html { redirect_to admin_drive_appointments_path(@appointment.drive) }
      format.js
    end
  end

  private
  def appointment_params
    params.require(:appointment).permit(
      :double_red, :slot_time, :day_id, :day_slot,
      user_attributes: [:id, :netid, :email, :fname, :lname, :class_year, :college, :lookup_by_email]
    )
  end
  def load_drive
    @drive = Drive.find params[:drive_id]
  end
end

app/helpers/admin/appointments_helper.rb
module Admin::AppointmentsHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def am_pm(slot)
    slot.strftime(Time::DATE_FORMATS[:am_pm])
  end

  def slot_row_id(day, slot)
    "slot-row-#{day.id}-#{slot.strftime('%H%M%S')}"
  end
end

app/views/admin/appointments/_tds.html.slim
td = appt.user.lname
td = appt.user.fname
td = appt.day.date if appt.day
td = am_pm appt.slot_time if appt.day
td = appt.user.college
td = appt.user.class_year
td = link_to appt.user.email, edit_user_path(appt.user)
/td = appt.user.phone
td = appt.double_red?
td = link_to appt.user.netid, edit_user_path(appt.user)
td
  - if appt.last_reminded_at
    .timestamp
      = time_vs_now(appt.last_reminded_at) 
  - else
    = button_to "remind", remind_drive_appointment_path(appt.drive, appt), class: 'btn btn-warning btn-xs', remote: true
td = link_to 'edit', edit_drive_appointment_path(appt.drive, appt), target: '_blank'

app/views/admin/appointments/index.html.slim
h1
  small> Appointments for
  = @drive.name

p.text-warning Click on a column header to sort
table.table.table-condensed.table-striped
  thead
    tr.info
      th = sorting_link 'users.lname', 'Last name'
      th = sorting_link 'users.fname', 'First name'
      th = sorting_link 'days.date', 'Date'
      /th = sorting_link 'exact_time', 'Time'
      th Time
      th = sorting_link 'users.college', 'College'
      th = sorting_link 'users.class_year', 'Class'
      th = sorting_link 'users.email', 'Email'
      /th Phone
      th = sorting_link 'double_red', 'Double?'
      th = sorting_link 'users.netid', 'Netid'
      th = sorting_link 'last_reminded_at', 'Last reminded'
      th 
  tbody
    - @appointments.each do |appt|
      = content_tag_for :tr, appt
        = render 'tds', appt: appt