config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin/cms'
  mount RailsEmailPreview::Engine, at: 'admin/emails'
  resources :appointments, only: [:index] do
    collection do
      get :by
    end
  end

  get 'sign_in' => 'home#sign_in'

  resources :users do
    post 'update_roles', on: :collection
  end
  resources :drives, only: [:show] do
    resources :appointments, except: [:index] do
      post :remind, on: :member
    end
    member do
      get 'kiosk'
      post 'add_appointment'
    end
  end
  resources :drives, only: [:edit, :update, :index]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  namespace :admin do
    resources :drives, only: [:show] do
      resources :appointments, only: [:index]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :lookup_by_email

  ROLES = ['admin', 'staff', '']

  validates :netid, uniqueness: {allow_blank: true}
  validates :email, uniqueness: {allow_blank: true}
  validates :email, presence: true, if: Proc.new {|user| user.netid.blank?}
  validates :role, inclusion: {in: ROLES}
  validate :require_netid_or_email

  has_many :appointments, dependent: :destroy
  has_many :drives, through: :appointments
  before_save :fetch_if_yale_email
  before_validation :normalize_role
  before_validation :merge_account_if_applicable

  def at_least_staff?
    staff? || admin?
  end

  def admin?
    role == 'admin'
  end

  def staff?
    role == 'staff'
  end

  def member?
    role.blank? || role == 'donor'
  end

  def has_role?(some_role)
    case some_role
    when 'staff'
      at_least_staff?
    when 'admin'
      admin?
    when 'donor'
      %w(donor staff admin).include?(role)
    else
      false
    end
  end

  def fetch_from_ldap
    raise "need email address" if email.blank?
    if user = YaleLDAP.lookup(email: email)
      self.fname = user[:first_name]
      self.lname = user[:last_name]
      self.class_year = user[:class_year]
      self.college = user[:college]
    end
  rescue Exception => e
  ensure
    self
  end

  def lookup_by_email?
    @lookup_by_email == '1'
  end

  def email_or_netid
    email.presence || netid
  end

  def display
    "#{full_name} <#{email_or_netid}>"
  end

  def full_name
    "#{fname} #{lname}"
  end

  private
  def fetch_if_yale_email
    if lookup_by_email? && yale_email?
      fetch_from_ldap
    end
    self.lookup_by_email = nil
  end

  def yale_email?
    email.present? && email.match(/@(.*)yale\.edu(.*)/)
  end

  def normalize_role
    self.role ||= ''
  end

  def require_netid_or_email
    if netid.blank? && email.blank?
      self.errors.add :base, "requires either Netid or Email"
    end
  end

  def merge_account_if_applicable
    # if there is another record with the same email but without netid
    if email.present? && (other = User.where(email: email, netid: '').first)
      # move all appointments to this account
      other.appointments.update_all("user_id = #{id}")
      other.destroy
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  def index
    # TODO pagination
    @users = User.order('role DESC, created_at').all
    authorize @users
  end

  def update_roles
    authorize :users, :index?
    if params[:roles_for]
      params[:roles_for].each do |user_id, role|
        User.find(user_id).update_attribute :role, role
      end
    end
    flash[:success] = "Roles updated."
    redirect_to action: 'index'
  end

  def edit
    check_user
    authorize @user
  end

  def update
    check_user
    if @user.update_attributes user_params
      flash[:success] = "Changes saved!"
    else
      flash[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
    end
    redirect_to edit_user_path(@user == current_user ? :current : @user)
  end

  private
  def user_params
    params.require(:user).permit(:fname, :lname, :college, :class_year, :email, :lookup_by_email, :phone, :role)
  end

  def check_user
    if params[:id] == 'current'
      @user = current_user
    else
      @user = User.find params[:id]
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.slim
- if @user == current_user
  h1 Your Profile
- else
  h1 Edit #{@user.display}

= simple_form_for @user do |f|
  - if params.has_key?(:roleplay)
    .alert.alert-danger
      = f.input :role, as: :select, collection: User::ROLES, hint: "For testing only. This option must be removed before launch."
  = render 'appointments/user_fields', u: f
  = f.submit "Save Changes", class: 'btn btn-primary', data: {disable_with: 'Saving...'}

app/views/users/index.html.slim
h1 Users

= form_tag update_roles_users_path do
  p
    = submit_tag "Update Checked Roles", class: 'btn btn-primary', data: {confirm: "After this, please double check who are admin and who are staff :)"}
  table.table.table-condensed
    thead
      tr
        th Set New Role?
        th Netid
        th Email
        th First Name
        th Last Name
        th Class Year
        th College
        th Created
        th Appointments
        th
    tbody
      - @users.each do |user|
        tr class=('info' if user == current_user) class=('text-danger' if user.admin?) class=('text-warning' if user.staff?)
          td
            .btn-group.btn-group-sm data-toggle="buttons" style="width:140px"
              label.btn class=(user.admin? ? 'btn-default active' : 'btn-default')
                => radio_button_tag "roles_for[#{user.id}]", 'admin'
                ' admin
              label.btn class=(user.staff? ? 'btn-default active' : 'btn-default')
                => radio_button_tag "roles_for[#{user.id}]", 'staff'
                ' staff
              label.btn class=(user.member? ? 'btn-default active' : 'btn-default')
                => radio_button_tag "roles_for[#{user.id}]", ''
                ' &times
          td = user.netid
          td
            span.label.label-info
              = user.role
            =< user.email
          td = user.fname
          td = user.lname
          td = user.class_year
          td = user.college
          td.timestamp = user.created_at.to_s(:am_pm_long)
          td = link_to user.appointments.count, by_appointments_path(user_id: user)
          td = link_to 'edit', [:edit, user], class: 'btn btn-default', target: '_blank'