config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin/cms'
  mount RailsEmailPreview::Engine, at: 'admin/emails'
  resources :appointments, only: [:index] do
    collection do
      get :by
    end
  end

  get 'sign_in' => 'home#sign_in'

  resources :users do
    post 'update_roles', on: :collection
  end
  resources :drives, only: [:show] do
    resources :appointments, except: [:index] do
      post :remind, on: :member
    end
    member do
      get 'kiosk'
      post 'add_appointment'
    end
  end
  resources :drives, only: [:edit, :update, :index]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  namespace :admin do
    resources :drives, only: [:show] do
      resources :appointments, only: [:index]
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_html_head.html.slim
head
  meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
  title Yale Red Cross
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/layouts/_navbar.html.slim
.navbar class=(current_admin ? 'navbar-inverse' : 'navbar-default')
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar-main"
        span.icon-bar
        span.icon-bar
        span.icon-bar

    .navbar-collapse.collapse id="navbar-main" style="height:1px"
      ul.nav.navbar-nav
        li = link_to "Home", '/'
        li = link_to "yale.edu/redcross", 'http://yale.edu/redcross/'
      ul.nav.navbar-nav.navbar-right
        - unless current_user
          li = link_to 'Sign in', sign_in_path, data: {disable_with: "Connecting to Yale server..."}
        - else
          li.btn-group
            a.dropdown-toggle data-toggle="dropdown" href="#"
              => current_user.email_or_netid
              - if current_user.role.present?
                .badge = current_user.role
            ul.dropdown-menu role="menu"
              li = link_to "Profile", edit_user_path(:current)
              li = link_to "Drives", drives_path
              li = link_to "Appointments", appointments_path
              - if current_user.admin?
                li.divider
                li = link_to "Admin Dashboard", '/admin'
                li = link_to "Users", users_path
                li = link_to "Email Templates", '/admin/emails'
              - if Rails.env.development?
                li.divider
                li = link_to 'letter_opener', '/letter_opener'
              li.divider
              li = link_to "Logout", '/logout?' + {gateway: true, service: root_url}.to_query

app/views/layouts/application.html.slim
doctype html
html
  = render 'layouts/html_head'

  body class="#{controller_name} #{action_name}"
    .wrapper
      .container
        = link_to root_url, class: 'thumbnail', style: 'border:none;margin-top:5px;margin-bottom:0' do
          = image_tag 'http://www.yale.edu/redcross/img/Red%20Cross%20Logo%203.png'
      = render 'layouts/navbar'

      / Main content
      div class="#{@container_fluid ? 'container-fluid' : 'container'}"
        - if flash.present?
          - flash.each do |name, msg|
            p[class="alert #{flasherize name}"] = msg
        == yield

    / Footer
    / = render 'layouts/footer'